@{
    issueConfigFile = "Probléme avec le fichier de conf."
    missingConfigFile = "fichier de conf introuvable."
    gitInstallation = "Installation de git"
    notInstalledIn = "non installé dans"
    gitClone = "installation avec git clone..."
    updateRequire = "Maj necessaire de"
    updateFrom = "depuis la"
    rebootCiv ="veuillez redemarrer Civilisation son script."
    upToDate = "est à jour"
    lauchGame = "Lancement de Civilization VI ..."
    lookUpdate = "recherche de mise à jour"
    goodBy = "Jeu eteint, Aurevoir!"
    askingUpdate = "Mettre à jour le mod ?"
    askToDeleteModNumber = "Supprimer lequel ?"
    askToDeleteMod = "Supprimer le Mod ?"
    yes = "o"
    modDeleted = "Mod supprimé"
    ModListGit = "Liste des Mods géré dans"
    test = "test"
    askToInstallModNumber = "Installé lequel ?"
    askToInstallMod = "Installé le mod ?"
    modInstall = "Mod installé"
    askToChangeTagModNumber = "Numero de version ?"
    askToChangeModNumber =  "Quel Mod à changer ?"
}